apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: w4tmgn0rx-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:da1ab83539aa1e71ebf35b1cfefa97d9baf90ab8@sha256:ec4b4c65a3069505be79c95851a54708e240c82e8b1c9498d0a1d8733e464bb1
          name: container-image
